INFILE &datafid PAD LRECL = 101;
INPUT
    @         1     PEFAMID                          $     5.  /*      1 -      5 */
    @         6     PWEIGHT                               12.4 /*      6 -     17 */
    @        18     REFATINC                         $     2.  /*     18 -     19 */
    @        20     REFGTR                           $     2.  /*     20 -     21 */
    @        22     REFMTINC                         $     2.  /*     22 -     23 */
    @        24     RWAOTPEN                         $     2.  /*     24 -     25 */
    @        26     RWAPRVAL                         $     2.  /*     26 -     27 */
    @        28     RWARPPG                          $     2.  /*     28 -     29 */
    @        30     RWARPPT                          $     2.  /*     30 -     31 */
    @        32     RWARRIF                          $     2.  /*     32 -     33 */
    @        34     RWARRSPL                         $     2.  /*     34 -     35 */
    @        36     RWASTBND                         $     2.  /*     36 -     37 */
    @        38     RWASTDEP                         $     2.  /*     38 -     39 */
    @        40     RWASTMUI                         $     2.  /*     40 -     41 */
    @        42     RWASTOIN                         $     2.  /*     42 -     43 */
    @        44     RWASTONF                         $     2.  /*     44 -     45 */
    @        46     RWASTRST                         $     2.  /*     46 -     47 */
    @        48     RWASTSTK                         $     2.  /*     48 -     49 */
    @        50     RWASTVHE                         $     2.  /*     50 -     51 */
    @        52     RWATFS                           $     2.  /*     52 -     53 */
    @        54     RWATOTPG                         $     2.  /*     54 -     55 */
    @        56     RWATOTPT                         $     2.  /*     56 -     57 */
    @        58     RWBUSEQ                          $     2.  /*     58 -     59 */
    @        60     RWDPRMOR                         $     2.  /*     60 -     61 */
    @        62     RWDSLOAN                         $     2.  /*     62 -     63 */
    @        64     RWDSTCRD                         $     2.  /*     64 -     65 */
    @        66     RWDSTLOC                         $     2.  /*     66 -     67 */
    @        68     RWDSTODB                         $     2.  /*     68 -     69 */
    @        70     RWDSTOMR                         $     2.  /*     70 -     71 */
    @        72     RWDSTVHN                         $     2.  /*     72 -     73 */
    @        74     RWDTOTAL                         $     2.  /*     74 -     75 */
    @        76     RWEIGHT                          $     2.  /*     76 -     77 */
    @        78     RWNETWPG                         $     2.  /*     78 -     79 */
    @        80     RWNETWPT                         $     2.  /*     80 -     81 */
    @        82     RATTCRLM                         $     2.  /*     82 -     83 */
    @        84     RASRCST                          $     2.  /*     84 -     85 */
    @        86     RASR1MFA                         $     2.  /*     86 -     87 */
    @        88     REXMG1A                          $     2.  /*     88 -     89 */
    @        90     RINHERT                          $     2.  /*     90 -     91 */
    @        92     VERDATE                          $    10.  /*     92 -    101 */
              ;
 
