proc format;
    VALUE    $A00047F
                    1 = "Oui, principalement à temps plein"
                    2 = "Oui, principalement à temps partiel"
                    3 = "N'a pas travaillé"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00012F
                   10 = "Terre-Neuve et Labrador"
                   11 = "Île-du-Prince-Édouard"
                   12 = "Nouvelle-Écosse"
                   13 = "Nouveau-Brunswick"
                   24 = "Québec"
                   35 = "Ontario"
                   46 = "Manitoba"
                   47 = "Saskatchewan"
                   48 = "Alberta"
                   59 = "Colombie-Britannique"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00035F
                   01 = "Aucun revenu"
                   02 = "Salaires et traitements"
                   03 = "Revenu d'un travail autonome"
                   04 = "Transferts gouvernementaux"
                   05 = "Revenu de placements"
                   06 = "Pensions de retraite"
                   07 = "Autre revenu"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00050F
                    1 = "Dispose d'un REER et n'en a jamais retiré de fonds"
                    2 = "Dispose ou disposait d'un REER et en a retiré des fonds"
                    3 = "N'a jamais eu de REER"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00051F
                    1 = "Maison individuelle non attenante"
                    2 = "Maison jumelée,maison en rangée ou en terrasse, duplex"
                    3 = "Appartement"
                    4 = "Autres"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00052F
                    1 = "Atlantique"
                    2 = "Québec"
                    3 = "Ontario"
                    4 = "Prairies"
                    5 = "Colombie Britannique"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00053F
                    1 = "Moins que secondaires"
                    2 = "Diplôme d'études secondaires"
                    3 = "Certificat ou diplôme post-secondaires non universitaire"
                    4 = "Diplôme ou certificat universitaire"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00059F
                    1 = "1 ou 2 cartes"
                    2 = "3 ou 4 cartes"
                    3 = "5 cartes ou plus"
                    4 = "Ne possède pas de cartes de crédit"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00074F
                   01 = "0 % - 1,99 %"
                   02 = "2 % - 2,49 %"
                   03 = "2,5 % - 2,99 %"
                   04 = "3 % - 3,49 %"
                   05 = "3,50 % - 3,99 %"
                   06 = "4 % - 4.99 %"
                   07 = "5 % et plus"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00078F
                    1 = "Employé"
                    2 = "Travailleur autonome ou travailleur non rémunéré"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $D00085F
                   01 = "Mois de 20 ans"
                   02 = "20 à 24 ans"
                   03 = "25 à 29 ans"
                   04 = "30 à 34 ans"
                   05 = "35 à 39 ans"
                   06 = "40 à 44 ans"
                   07 = "45 à 49 ans"
                   08 = "50 à 54 ans"
                   09 = "55 à 59 ans"
                   10 = "60 à 64 ans"
                   11 = "65 à 69 ans"
                   12 = "70 à 74 ans"
                   13 = "75 à 79 ans"
                   14 = "80 ans et plus"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE    $D00086F
                    1 = "Personne seule"
                    2 = "Couple, sans enfant"
                    3 = "Couple, avec des enfants et Famille monoparentale"
                    4 = "Autres types de famille"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE    $YESN01F
                    1 = "Oui"
                    2 = "Non"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     A00012F
                    1 = "Fixe"
                    2 = "Variable"
                    3 = "Combinaison (hybride)"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     A00050F
                    1 = "Mensuellement"
                    2 = "Aux deux semaines"
                    3 = "À la semaine"
                    4 = "Deux fois par mois"
                    5 = "Autre - Précisez"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     A00074F
                    1 = "Moins que le montant minimum exigé?"
                    2 = "Le montant minimum exigé?"
                    3 = "Plus que le minimum mais moins que le montant complet?"
                    4 = "Le montant complet?"
                    5 = "Les cartes de crédit n’étaient pas utilisées."
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     A00086F
                    1 = "Augmentera"
                    2 = "Diminuera"
                    3 = "Pareille"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00025F
                    1 = "Propriétaire sans hypothèque"
                    2 = "Propriétaire avec une hypothèque"
                    3 = "Non propriétaire"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00058F
                    0 = "Aucun"
                    1 = "1"
                    2 = "2"
                    3 = "3 ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00061F
                    1 = "1 personne"
                    2 = "2 personnes"
                    3 = "3 personnes"
                    4 = "4 personnes"
                    5 = "5 personnes ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00070F
                    1 = "1"
                    2 = "2"
                    3 = "3"
                    4 = "4 ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00071F
                    1 = "1"
                    2 = "2 ou plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00072F
                   01 = "3 ou 6 mois"
                   02 = "1 an"
                   03 = "2 ans"
                   04 = "3 ans"
                   05 = "4 ans"
                   06 = "5 ans"
                   07 = "7 ou 10 ans"
                   08 = "Autre"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE     D00073F
                   00 = "0 %"
                   01 = "1 % - 10 %"
                   02 = "11 % - 20 %"
                   03 = "21 % - 30 %"
                   04 = "31 % - 40 %"
                   05 = "41 % - 50 %"
                   06 = "51 % - 60 %"
                   07 = "61 % - 70 %"
                   08 = "71 % - 99 %"
                   09 = "100 %"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE     D00075F
                    1 = "20 000 et moins"
                    2 = "20 001 à 40 000"
                    3 = "40 001 à 80 000"
                    4 = "80 001 et plus"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     D00076F
                   01 = "Moins de 5 ans"
                   02 = "5 à 9 ans"
                   03 = "10 à 14 ans"
                   04 = "15 à 19 ans"
                   05 = "20 à 24 ans"
                   06 = "25 ans et plus"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE     D00087F
                   01 = "Avant 1961"
                   02 = "1961 - 1970"
                   03 = "1971 - 1980"
                   04 = "1981 - 1990"
                   05 = "1991 - 2000"
                   06 = "2001 - 2005"
                   07 = "2006 - 2010"
                   08 = "2011 - 2015"
                   09 = "2016 - 2017"
                   10 = "2018 - 2019"
                   96 = "Enchaînement valide"
                   97 = "Ne sait pas"
                   98 = "Refus"
                   99 = "Non déclaré"
                    ;
    VALUE     D00088F
                 2019 = "2019"
                 2020 = "2020"
                 2021 = "2021"
                 2022 = "2022"
                 2023 = "2023"
                 2024 = "2024 et plus"
                 9996 = "Enchaînement valide"
                 9997 = "Ne sait pas"
                 9998 = "Refus"
                 9999 = "Non déclaré"
                    ;
    VALUE     D00089F
                    1 = "0-14 ans"
                    2 = "15-24 ans"
                    3 = "25-29 ans"
                    4 = "30-40 ans"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     M00012F
                99996 = "Enchaînement valide"
                99997 = "Ne sait pas"
                99998 = "Refus"
                99999 = "Non déclaré"
                    ;
    VALUE     M00015F
               999996 = "Enchaînement valide"
               999997 = "Ne sait pas"
               999998 = "Refus"
               999999 = "Non déclaré"
                    ;
    VALUE     M00018F
             99999996 = "Enchaînement valide"
             99999997 = "Ne sait pas"
             99999998 = "Refus"
             99999999 = "Non déclaré"
                    ;
    VALUE     M00022F
            999999996 = "Enchaînement valide"
            999999997 = "Ne sait pas"
            999999998 = "Refus"
            999999999 = "Non déclaré"
                    ;
    VALUE     M00036F
         999999999996 = "Enchaînement valide"
         999999999997 = "Ne sait pas"
         999999999998 = "Refus"
         999999999999 = "Non déclaré"
                    ;
    VALUE     M00038F
         9999999.9996 = "Enchaînement valide"
         9999999.9997 = "Ne sait pas"
         9999999.9998 = "Refus"
         9999999.9999 = "Non déclaré"
                    ;
    VALUE     SEX002F
                    1 = "Masculin"
                    2 = "Féminin"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
    VALUE     YESN01F
                    1 = "Oui"
                    2 = "Non"
                    6 = "Enchaînement valide"
                    7 = "Ne sait pas"
                    8 = "Refus"
                    9 = "Non déclaré"
                    ;
 
