proc format;
    VALUE    $A00047F
                    1 = "Yes - mostly full-time"
                    2 = "Yes - mostly part-time"
                    3 = "No - did not work"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00012F
                   10 = "Newfoundland and Labrador"
                   11 = "Prince Edward Island"
                   12 = "Nova Scotia"
                   13 = "New Brunswick"
                   24 = "Quebec"
                   35 = "Ontario"
                   46 = "Manitoba"
                   47 = "Saskatchewan"
                   48 = "Alberta"
                   59 = "British Columbia"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00035F
                   01 = "No income"
                   02 = "Wages and salaries"
                   03 = "Self-employment income"
                   04 = "Government transfers"
                   05 = "Investment income"
                   06 = "Retirement pensions"
                   07 = "Other income"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00050F
                    1 = "Have RRSPs and have never made RRSP withdrawals"
                    2 = "Have or have had RRSPs and have made RRSP withdrawals"
                    3 = "Never had RRSPs"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00051F
                    1 = "Single detached"
                    2 = "Double/semi-detached,row or terrace,duplex"
                    3 = "Apartment"
                    4 = "Other"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00052F
                    1 = "Atlantic"
                    2 = "Quebec"
                    3 = "Ontario"
                    4 = "Prairies"
                    5 = "British Columbia"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00053F
                    1 = "Less than high school"
                    2 = "High school diploma"
                    3 = "Non-university post-secondary certificate or diploma"
                    4 = "University degree or certificate"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00059F
                    1 = "1 or 2 cards"
                    2 = "3 or 4 cards"
                    3 = "5 or more cards"
                    4 = "Does not own credit cards"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00074F
                   01 = "0% - 1.99%"
                   02 = "2% - 2.49%"
                   03 = "2.5% - 2.99%"
                   04 = "3% - 3.49%"
                   05 = "3.5% - 3.99%"
                   06 = "4% - 4.99%"
                   07 = "5% and over"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00078F
                    1 = "Employee"
                    2 = "Self-employed or working without pay"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $D00085F
                   01 = "Under 20 years"
                   02 = "20 to 24 years"
                   03 = "25 to 29 years"
                   04 = "30 to 34 years"
                   05 = "35 to 39 years"
                   06 = "40 to 44 years"
                   07 = "45 to 49 years"
                   08 = "50 to 54 years"
                   09 = "55 to 59 years"
                   10 = "60 to 64 years"
                   11 = "65 to 69 years"
                   12 = "70 to 74 years"
                   13 = "75 to 79 years"
                   14 = "80 years and older"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE    $D00086F
                    1 = "Unattached individual"
                    2 = "Couple, no children"
                    3 = "Couple with children and Lone-parent family"
                    4 = "Other family types"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE    $YESN01F
                    1 = "Yes"
                    2 = "No"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     A00012F
                    1 = "Fixed"
                    2 = "Variable"
                    3 = "Combination (hybrid)"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     A00050F
                    1 = "Monthly"
                    2 = "Every two weeks"
                    3 = "Weekly"
                    4 = "Twice a month"
                    5 = "Other - Specify"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     A00074F
                    1 = "Less than the minimum amount?"
                    2 = "The minimum amount?"
                    3 = "More than the minimum but less than the full amount?"
                    4 = "The full amount?"
                    5 = "The credit cards were not used."
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     A00086F
                    1 = "Increase"
                    2 = "Decrease"
                    3 = "Same"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00025F
                    1 = "Own without mortgage"
                    2 = "Own with mortgage"
                    3 = "Do not own"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00058F
                    0 = "None"
                    1 = "1"
                    2 = "2"
                    3 = "3 or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00061F
                    1 = "1 person"
                    2 = "2 persons"
                    3 = "3 persons"
                    4 = "4 persons"
                    5 = "5 persons or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00070F
                    1 = "1"
                    2 = "2"
                    3 = "3"
                    4 = "4 or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00071F
                    1 = "1"
                    2 = "2 or more"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00072F
                   01 = "3 or 6 months"
                   02 = "1 year"
                   03 = "2 years"
                   04 = "3 years"
                   05 = "4 years"
                   06 = "5 years"
                   07 = "7 or 10 years"
                   08 = "Other"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE     D00073F
                   00 = "0%"
                   01 = "1% - 10%"
                   02 = "11% - 20%"
                   03 = "21% - 30%"
                   04 = "31% - 40%"
                   05 = "41% - 50%"
                   06 = "51% - 60%"
                   07 = "61% - 70%"
                   08 = "71% - 99%"
                   09 = "100%"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE     D00075F
                    1 = "20,000 and under"
                    2 = "20,001 to 40,000"
                    3 = "40,001 to 80,000"
                    4 = "80,001 and over"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     D00076F
                   01 = "Under 5 years"
                   02 = "5 to 9 years"
                   03 = "10 to 14 years"
                   04 = "15 to 19 years"
                   05 = "20 to 24 years"
                   06 = "25 years and over"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE     D00087F
                   01 = "Before 1961"
                   02 = "1961 - 1970"
                   03 = "1971 - 1980"
                   04 = "1981 - 1990"
                   05 = "1991 - 2000"
                   06 = "2001 - 2005"
                   07 = "2006 - 2010"
                   08 = "2011 - 2015"
                   09 = "2016 - 2017"
                   10 = "2018 - 2019"
                   96 = "Valid skip"
                   97 = "Don't know"
                   98 = "Refusal"
                   99 = "Not stated"
                    ;
    VALUE     D00088F
                 2019 = "2019"
                 2020 = "2020"
                 2021 = "2021"
                 2022 = "2022"
                 2023 = "2023"
                 2024 = "2024 and over"
                 9996 = "Valid skip"
                 9997 = "Don't know"
                 9998 = "Refusal"
                 9999 = "Not stated"
                    ;
    VALUE     D00089F
                    1 = "0-14 years"
                    2 = "15-24 years"
                    3 = "25-29 years"
                    4 = "30-40 years"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     M00012F
                99996 = "Valid skip"
                99997 = "Don't know"
                99998 = "Refusal"
                99999 = "Not stated"
                    ;
    VALUE     M00015F
               999996 = "Valid skip"
               999997 = "Don't know"
               999998 = "Refusal"
               999999 = "Not stated"
                    ;
    VALUE     M00018F
             99999996 = "Valid skip"
             99999997 = "Don't know"
             99999998 = "Refusal"
             99999999 = "Not stated"
                    ;
    VALUE     M00022F
            999999996 = "Valid skip"
            999999997 = "Don't know"
            999999998 = "Refusal"
            999999999 = "Not stated"
                    ;
    VALUE     M00036F
         999999999996 = "Valid skip"
         999999999997 = "Don't know"
         999999999998 = "Refusal"
         999999999999 = "Not stated"
                    ;
    VALUE     M00038F
         9999999.9996 = "Valid skip"
         9999999.9997 = "Don't know"
         9999999.9998 = "Refusal"
         9999999.9999 = "Not stated"
                    ;
    VALUE     SEX002F
                    1 = "Male"
                    2 = "Female"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
    VALUE     YESN01F
                    1 = "Yes"
                    2 = "No"
                    6 = "Valid skip"
                    7 = "Don't know"
                    8 = "Refusal"
                    9 = "Not stated"
                    ;
 
