---
title: Carte des résultats des élections municipales de Montréal 2021
author: Simon
date: '2021-11-26'
slug: mtl2021
categories: []
tags: []
keywords:
  - tech
---

Merci d'accepter mon choix éditorial de couleurs.  

```{r setup, include =F, echo =F}
#
# TODO : valider ceci : Chunk options must be written in one line; no line breaks are allowed inside chunk options;
# https://yihui.name/knitr/options/
knitr::opts_chunk$set(echo = FALSE, 
                      collapse = FALSE,
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE,
                      #fig.align= "center",
                      #fig.width = 10,
                      highlight = TRUE,
                      cache = FALSE,
                      cache.lazy = FALSE
) # fixes long vecto rnot supported quand on cache des gros éléments https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script
```


```{r, echo = FALSE, out.width = "100%"}
library(stringr)
library(tidyverse)
library(sf)
library(mapview)
results <- read_csv("~/git/30DaysMapChallenge/2021_26_choropleth/resultats-detailles-2021.csv")
#bureaux  <- read_sf("2021_26_choropleth/bureaux-vote-2021.shp")
sections <- read_sf("~/git/30DaysMapChallenge/2021_26_choropleth/section-vote-2021.shp")
#bassins <- read_sf("2021_26_choropleth/bassins-electoraux-2021.shp")
#districts <- read_sf("2021_26_choropleth/districts-electoraux-2021.shp")
z <- results %>% mutate(
  NOM_SECTIO = paste0(stringr::str_pad(DistrictID, side = "left", pad = "0", width = 3) ,
                      "-",
                      stringr::str_pad(Bureau, side = "left", pad = "0", width = 3) )
) %>%
  filter(Poste ==0) %>% # mairie
  filter(Bureau <= 108)  %>% # vote en bureau
  mutate(pct = 100* Votes / TotalValidVotes) 

poll_winners <- z %>% 
  group_by(NOM_SECTIO ) %>%
  slice_max(pct) %>%
  select(NOM_SECTIO, winner= Candidat, pct_winner = pct )


zz <- z %>% 
  select(NOM_SECTIO, Candidat,  TotalValidVotes, TotalRejectedVotes, TotalVotes, pct ) %>%
  pivot_wider(names_from=Candidat, values_from = pct, names_prefix = "pct_") %>%
  left_join(poll_winners) %>% 
  janitor::clean_names() 


map_data <- sections %>%  
  janitor::clean_names() %>%
  inner_join(zz)   %>% 
  mutate(fct_winner = factor(winner),
         winner2 = case_when(
           winner == "PLANTE Valérie" ~ "Valérie Plante",
           winner == "CODERRE Denis" ~ "Denis Coderre",
           winner == "HOLNESS Balarama" ~ "Balarama Holness",
           is.na(winner)  ~ "No vote",
           TRUE ~ "Autre"
           
         ),
         fct_winner2 = factor(winner2, levels = c("Valérie Plante", "Denis Coderre", "Balarama Holness", "Autre", "No vote")),
         fct_winner = fct_explicit_na(fct_winner, na_level = "No winner")
  )%>% 
  
  st_cast( "MULTIPOLYGON") %>%
  st_cast("POLYGON") %>%
  mutate(my_opacity = floor(pmin(30+ pct_winner *2, 200))) %>%
  mutate(my_opacity = if_else(total_valid_votes ==0, 200, my_opacity))


library(mapdeck)
MAPBOX <- Sys.getenv("mapbox")



colors <- tibble(
  winner2 = c("Valérie Plante", "Denis Coderre", "Balarama Holness", "Autre", "No vote"),
  colour = c("#FFC0CB", "#684c2a",  "#003049", "#FFA500", "#00FF00")
)

l1 <- legend_element(
  variables = colors$winner2,
  colours = colors$colour,
  colour_type = "fill",
  variable_type = "category",
  title = "Gagnant"
)

js <- mapdeck_legend(l1)

map_data_plus <- map_data %>% 
  left_join(colors) %>%
  mutate(colour = paste0(colour,as.hexmode(my_opacity))) %>%
  mutate(my_tooltip = paste0(nom_sectio, ": ",winner, " (", round(pct_winner,1), " % de ", total_valid_votes, " votes)"))  %>%
  st_transform(4326)

mymap <- mapdeck(token = MAPBOX, 
                 style = mapdeck_style('light'))  %>% #  # 
  add_polygon(data = map_data_plus   ,
              fill_colour = "colour",
              legend = js,
              auto_highlight = TRUE,
              highlight_colour = "#FFFFFFAA",
              tooltip = "my_tooltip"
              
              
  )

widgetframe::frameWidget(mymap, height =1000)

```

